### ISSUE TITLE
The GPU utilization is low in Latent mode and processing speed is too slow.

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [hako-mikan/sd-webui-regional-prompter#207] opened 2023-08-21 08:37 UTC
First of all, thanks for creating such a great extension!

However, I encountered some performance bottleneck issues while using it.

When using the Latent type and multiple LoRa models to generate multiple human characters in a single picture, the process is quite slow. 

Here is the observation:
When generating a 640x480 image, the time cost is as follows:
Direct generation with no restore faces nor hires: 4 seconds (avg, and utilization will up to 100%)
Using regional prompts in latent mode with no restore faces nor hires: 43 seconds (avg, and utilization will never higer than 40%)

The maximum GPU utilization during generation is lower than 40%, and the actual graphic memory usage is lower than 20% (running alongside other instances). 

And that creates a lot of trouble when generating batched results for comparison. For every 9 pictures, it takes over 6 minutes per batch, whereas it used to be less than 40 seconds.

Here is my promt and works well:
```
photo,masterpiece,model_suesy,model_dennis, sitting,smile, looking at viewer,canteen,ADDCOMM
model_suesy, pink suit,<lora:model_suesy:0.8:0.8>,ADDCOL
table,ADDCOL
model_dennis, short hair, white suit,<lora:model_dennis:0.8:0.8>
```

Here is some basic parameters:
Sampling steps=20
Resolution=640X480
CFG Scale=7
Sampling method=DPM++ SDE Karras
**Has a openpose in controlNet like below**
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/58684828/c36e0e96-9657-4f0f-9d74-49a04fbe6a41)

Here is the regional prompt settings:
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/58684828/dac2c6ef-2f68-48c1-a042-0f8752425b1c)

Is there anyting that I'm wrong while using the extension? Or is it possible to expedite the processing in the latent mode to optimizing the utilization of hardware resources?

**Comment by hako-mikan** [comment] 2023-08-22 15:41
This is due to a bug in the web-ui.
A fix request for this bug has been submitted, and it should be resolved in a future version. 
Therefore, it should be faster once we reach web-ui 1.6.

**Comment by hako-mikan** [comment] 2023-09-01 11:39
You should be able to resolve the issue by updating the Web-UI and this extension. Give it a try.

**Comment by InitialDet** [comment] 2023-09-01 17:33
Using the latest version, latent mode still is only using around 50% of the gpu (rtx 3090)

**Comment by hako-mikan** [comment] 2023-09-02 01:01
In Latent mode, there may be a reduced GPU usage compared to normal operation because separate processing is required for each region. This is by design and not a bug.

**Closed** 2023-09-04 16:38 UTC

**Comment by Kamekos** [comment] 2023-10-20 21:17
Speed is definitely way way slower than before in Latent mode, it takes me twice or thrice much time than a few months ago
