### ISSUE TITLE
Error : 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Kaneda56** [hako-mikan/sd-webui-regional-prompter#307] opened 2024-03-09 08:59 UTC
I was able to generate many images and suddenly I got this error and I can't generate images anymore

```
1,1 0.2 Horizontal
Regional Prompter Active, Pos tokens : [10, 10], Neg tokens : [77]
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "S:\Forge\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "S:\Forge\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\modules\txt2img.py", line 111, in txt2img_function
    processed = processing.process_images(p)
  File "S:\Forge\stable-diffusion-webui-forge\modules\processing.py", line 752, in process_images
    res = process_images_inner(p)
  File "S:\Forge\stable-diffusion-webui-forge\modules\processing.py", line 922, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "S:\Forge\stable-diffusion-webui-forge\modules\processing.py", line 1275, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "S:\Forge\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "S:\Forge\stable-diffusion-webui-forge\modules\sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "S:\Forge\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "S:\Forge\stable-diffusion-webui-forge\modules_forge\forge_sampler.py", line 88, in forge_sample
    denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 289, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\modules\samplers.py", line 258, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\modules\model_base.py", line 90, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 867, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 55, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 620, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 447, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\util.py", line 194, in checkpoint
    return func(*inputs)
  File "S:\Forge\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 547, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2, transformer_options=extra_options)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: hook_forward.<locals>.forward() got an unexpected keyword argument 'transformer_options'
hook_forward.<locals>.forward() got an unexpected keyword argument 'transformer_options'
*** Error completing request
*** Arguments: ('task(xlhtzx9q2r5xqa8)', <gradio.routes.Request object at 0x0000015F8DD51210>, '2 boys, 14yo\nBREAK\nblonde hair boy\nBREAK\nbrown hair boy', '', ['Negative prompt'], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', True, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, True, False, 'Attention', [False], '0', '0', '0.4', None, '0', '0', False, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, [], 30, '', 4, [], 1, '', '', '', '') {}
    Traceback (most recent call last):
      File "S:\Forge\stable-diffusion-webui-forge\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable
```

**Comment by Heather95** [comment] 2024-03-09 12:16
Forge UI will give NoneType errors at random sometimes when using non-default extensions. Try to reload the UI and let us know if that fixes it with the same settings/prompt. I'm no expert, but it looks like maybe that error lies with ADetailer, not Regional Prompter.

See this Forge issue where many others have received NoneType errors when using outside extensions:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/181

**Comment by Kaneda56** [comment] 2024-03-09 12:29
> Forge UI will give NoneType errors at random sometimes when using non-default extensions. Try to reload the UI and let us know if that fixes it with the same settings/prompt. I'm no expert, but it looks like maybe that error lies with ADetailer, not Regional Prompter.
> 
> See this Forge issue where many others have received NoneType errors when using outside extensions: [lllyasviel/stable-diffusion-webui-forge#181](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/181)

I restart the server and disactivate ADetailer but error still here

**Comment by sanoken0417** [comment] 2024-03-09 16:37
Sorry for the sudden.
I also suddenly got the same error with foge.

**Comment by sanoken0417** [comment] 2024-03-09 17:46
No error occurred with A1111_v1.8.

**Comment by sanoken0417** [comment] 2024-03-09 18:20
Even in A1111_v1.8, something goes wrong when I turn on "FP8 weight".

**Comment by Heather95** [comment] 2024-03-09 21:36
> Sorry for the sudden. I also suddenly got the same error with foge.

Sorry, guys, you're correct. I received NoneType error when using RP in Forge, but no error in A1111. I should have tested first before I replied. It worked correctly a couple of days ago.

I disabled every extension (including built-in) except for Regional Prompter and still received the error. When I disabled RP, I did not get an error.

@Kaneda56 You could open an issue on the Forge repository: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues
A different issue exists there about support for RP in img2img, and they've already made some progress on it, so they will probably want to help with this issue too.

**Comment by Heather95** [comment] 2024-03-09 22:00
Hey @Kaneda56 @sanoken0417 
Regional Prompter is working on an older commit version of Forge.
For a temporary fix, you will have to revert to "b9705c5."
If you don't know how to do that, you can use [Stability Matrix](https://github.com/LykosAI/StabilityMatrix).

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/37752957/c093b605-6e95-4ee0-8769-9b847a461934)

**Comment by CamiKaa** [comment] 2024-03-09 23:23
I'm getting that error even after reverting to Forge b9705c5 commit 😔

**Comment by Heather95** [comment] 2024-03-10 11:12
> I'm getting that error even after reverting to Forge b9705c5 commit 😔

@CamiKaa Sorry to hear that. It's working for me.

I suggest the following:
1. Disable all extensions except for built-in and Regional Prompter. (You may receive an error with built-in disabled.)
2. Make sure you have updated RP to the latest commit 59d68e6e.
3. Use RP in Attention mode. Forge does not support Latent mode (yet).

Hopefully, a future Forge update will fix these issues.

The prompts I used in Forge b9705c5:
- 2boys BREAK blonde hair BREAK black hair
- 1girl BREAK blonde hair BREAK black hair

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/37752957/159e030b-1d2a-4f1f-9e4f-84dc3e712836)

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/37752957/bfd200c8-750f-4b69-a783-d8ad580d956a)

**Comment by sanoken0417** [comment] 2024-03-10 11:38
I didn't do well.
Use 1.8 when using PR.

version: [f0.0.17v1.8.0rc-latest-276-g29be1da7]  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [1449e5b0b9]

**Comment by Heather95** [comment] 2024-03-10 11:55
> I didn't do well. Use 1.8 when using PR.
> 
> version: [f0.0.17v1.8.0rc-latest-276-g29be1da7]  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [1449e5b0b9]

@sanoken0417 Hello,
You will have to go back to an older "commit" of Forge.
Please try commit version: **b9705c58**
Here is my information.  version: [f0.0.17v1.8.0rc-latest-273-gb9705c58]  •  python: 3.10.11  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [86d2b2ed69]

If you are not familiar with Git, you can try [my other option here](https://github.com/hako-mikan/sd-webui-regional-prompter/issues/307#issuecomment-1986991427).

**Comment by CamiKaa** [comment] 2024-03-11 08:20
@Heather95 I did a cleanup on my extensions, made sure to hard reset to commit b9705c5 and now it's working again!
No idea what was conflicting to be honest, but at least it's working once again. Thank you for the help!

**Comment by Heather95** [comment] 2024-03-11 14:25
> @Heather95 I did a cleanup on my extensions, made sure to hard reset to commit b9705c5 and now it's working again! No idea what was conflicting to be honest, but at least it's working once again. Thank you for the help!

That's great, glad to hear you got it working. You're welcome! @CamiKaa

**Comment by sanora87** [comment] 2024-03-12 00:16
>roll back to "b9705c5"

I wish I knew how to do this. I tried using a youtube tutorial and just got errors for my troubles.

**Comment by Yumeno** [comment] 2024-03-12 11:25
> @Heather95 I did a cleanup on my extensions, made sure to hard reset to commit b9705c5 and now it's working again! No idea what was conflicting to be honest, but at least it's working once again. Thank you for the help!

I did the same and it worked well, but when I combined it with ControlNet, it still gave me an error.

**Comment by Heather95** [comment] 2024-03-13 18:57
> > roll back to "b9705c5"
> 
> I wish I knew how to do this. I tried using a youtube tutorial and just got errors for my troubles.

@sanora87 Hello, I'm sorry to hear that. I can give a little instructions about how to do it with Stability Matrix. It takes around 10 minutes.
I am not affiliated with Matrix or RP, but I use both of them often.

1. [Install Matrix](https://github.com/LykosAI/StabilityMatrix/releases/)
2. Choose directory. Continue. "Skip first-time setup" (bottom button). Press the three lines button in top left corner.
3. Go to Packages. "+ Add Package." WebUI Forge. Advanced Options. "Commit": b9705c5. Install.
4. (Optional) Go to Checkpoints. "Models Folder." Copy your existing models into there.
5. Go to Launch. Press "Launch" button. After Forge opens, install RP extension. Apply and quit. Press "Launch" button in Matrix again.

Good luck!

> I did the same and it worked well, but when I combined it with ControlNet, it still gave me an error.

@Yumeno Sorry, but I haven't tested RP with ControlNet. It might not be possible. :(

**Comment by kai-rin** [comment] 2024-03-17 14:14
I am also encountering the same issue. I haven't tried rolling back, but I wanted to post a comment to let you know that there are other users experiencing this problem as well. I always find this extension incredibly useful, and I'm grateful for the hard work put into its development and maintenance.

**Comment by gohan2091** [comment] 2024-03-25 23:26
I'm getting the same error "TypeError: 'NoneType' object is not iterable" and my Forge is up-to date. Anyone can help?

**Comment by Heather95** [comment] 2024-03-29 01:27
> I'm getting the same error "TypeError: 'NoneType' object is not iterable" and my Forge is up-to date. Anyone can help?

@gohan2091 Until the fix is merged into Regional Prompter, you have 2 options right now:
1) Revert Forge to commit b9705c5. See previous comments if you don't know how to do that.
**or**
2) Install the PR fork as an extension in current version Forge with this link. You should probably delete the old Prompter folder in extensions first. https://github.com/catboxanon/sd-webui-regional-prompter.git

**Comment by gmf1982** [comment] 2024-03-29 07:32
This error also occurred when I used Controlnet Tile, but it disappeared when I replaced the model, So I think it is caused by model mismatch。
![PixPin_2024-03-29_15-30-07](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/130820234/6235bed6-b5aa-4e14-a706-60b583aceaec)

**Comment by Kaneda56** [comment] 2024-04-01 07:04
> 2. Install the PR fork as an extension in current version Forge with this link. You should probably delete the old Regional Prompter folder in extensions first. https://github.com/catboxanon/sd-webui-regional-prompter.git

I have the same error with this extension

**Closed** 2024-04-02 10:11 UTC

**Comment by jeflehardi** [comment] 2024-06-23 23:40
> Hé@Kaneda56 @sanoken0417 Regional Prompter travaille sur une ancienne version de validation de Forge. Pour une solution temporaire, vous devrez revenir à « b9705c5 ». Si vous ne savez pas comment faire cela, vous pouvez utiliser [Stability Matrix](https://github.com/LykosAI/StabilityMatrix) .

thanks a lot; it's run !
